-role=index
-conf=./conf/index.yaml
-coor_url=file://./conf/coor_list
-omp_num_threads=1
-vector_operation_parallel_thread_num=16
-max_hnsw_memory_size_of_region=2147483648
-vector_max_batch_count=4096
-hnsw_max_init_max_elements=40000
-braft_use_align_hearbeat=false
-dingo_trace_append_entry_latency=true
-raft_sync=true
-free_memory_to_system_interval=60
-enable_dir_service=false
-enable_threads_service=false
-dingo_log_switch_txn_detail=false
-dingo_log_switch_txn_gc_detail=false
-dingo_log_switch_scalar_speed_up_detail=false
-service_log_threshold_time_ns=10000000000
-enable_vector_index_diskann=true
-dingo_log_switch_diskann_detail=false
-read_worker_num=128
-read_worker_max_pending_num=1024
-write_worker_num=128
-write_worker_max_pending_num=1024
-apply_worker_num=64
-apply_worker_max_pending_num=1024
-enable_coprocessor_v2_statistics_time_consumption=false
-raft_meta_enable_leveldb_tuning=true
-raft_meta_enable_preserialize=true
-raft_meta_force_no_sync=true
-raft_meta_periodic_sync_enabled=false
-raft_meta_periodic_sync_interval_ms=1000
-raft_latency_log_batch_append_entries=true
-raft_latency_log_append_entries=true
-raft_latency_log_handle_append_entries=true
-raft_latency_log_init=true
-rocks_log_enable_get_term_cache=true
-store_state_machine_enable_independent_queue=false
-print_recycle_orphan_region_not_table_or_index=false
-print_process_job_error=true
-print_periodic_merge_check=false
-print_periodic_split_check=false
-print_raft_add_node=true
-max_restore_data_memory_size=10485760
-max_restore_count=32768
-raft_latency_log_threshold_ms=1000
