name: CMake_rocky

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    container: dingodatabase/dingo-store-rocky-8-dev:latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Safe Dir
      run: git config --global --add safe.directory $PWD

    - name: Clone Submodule
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: git submodule update --init --recursive 

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: source /opt/intel/oneapi/setvars.sh && cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DTHIRD_PARTY_BUILD_TYPE=${{env.BUILD_TYPE}} -DWITH_MKL=ON -DBUILD_UNIT_TESTS=OFF -DBRPC_ENABLE_CPU_PROFILER=OFF -DLINK_TCMALLOC=ON -DROCKSDB_PROTABLE_OPTION=1
 
    - name: Build
      # Build your program with the given configuration
      run: source /opt/intel/oneapi/setvars.sh && cmake --build ./build --config ${{env.BUILD_TYPE}}


    - name: Archive the dingo directory
      run: |
        tar -czvf dingo-store.tar.gz  scripts build/bin/dingodb* conf/ 

    - name: copy artifactory to another workflow
      uses: actions/upload-artifact@v2
      with:
          name: dingo-store.tar.gz
          path: ./dingo-store.tar.gz


