name: Java_Maven_Build

on:
  push:
    branches: [ quickBI-v4.0.0 ]
  pull_request:
    branches: [ quickBI-v4.0.0 ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Initialize protocol definitions
      run: git submodule update --init dingo-store-proto

    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and test
      working-directory: java
      run: mvn -B -ntp clean verify -Dgpg.skip=true